EOW 4: Added the vital attributes for the character
x13enos/edge_of_world pull request #2
Opened 2016-11-06 19:26 UTC by x13enos

2016-11-06 19:32 UTC, x13enos commented
Test this, please.

2016-11-13 17:46 UTC, kryachkov commented
Let's not keep stuff in `./lib` folder. Lets move all to `app`. Thus we will not need that autoload magic

2016-11-13 17:48 UTC, kryachkov requested changes

2016-11-13 17:48 UTC, kryachkov commented on config/application.rb
> +    config.autoload_paths += %W( #{config.root}/lib )
Better move stuff to `app` and get rid of this sh..

2017-05-15 16:06 UTC, closed without merging